[package]
name = "lesson3"
version = "0.1.0"
edition = "2021"

[dependencies]
winit = "0.26"
env_logger = "0.9"
log = "0.4"
wgpu = "0.13"
tokio = { version = "1.0.21", features = ["full"] }
bytemuck = { version = "1.4", features = ["derive"] }