[package]
name = "rust_wgpu_tutorial"
version = "0.1.0"
edition = "2021"

[workspace]

members = [
    "lesson1",
    "lesson2",
    "lesson3",
    "lesson4",
    "lesson5",
    "lesson6"
]

[dependencies]
